exclude: conf.py
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: double-quote-string-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
- hooks:
  - additional_dependencies:
    - flake8-typing-imports==1.5.0
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - id: autopep8
  repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
- hooks:
  - id: validate_manifest
  repo: https://github.com/pre-commit/pre-commit
  rev: v1.21.0
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v1.25.3
- hooks:
  - args:
    - --py3-plus
    id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v1.9.0
- hooks:
  - args:
    - --py36-plus
    id: add-trailing-comma
  repo: https://github.com/asottile/add-trailing-comma
  rev: v1.5.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.8
