language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_script:
    - pip install poetry
    - poetry install
script:
    - poetry run codecov

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
