site_name: Photoshop Python API
repo_url: https://github.com/loonghao/photoshop-python-api
repo_name: github
site_author: longhao
remote_branch: master
copyright: "Copyright (c) 2019 Long Hao"

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: docs

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Examples: examples.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- 'Issue Tracker': 'https://github.com/loonghao/photoshop-python-api/issues'

markdown_extensions:
  - pymdownx.extra
  - admonition
  - def_list
  - footnotes
  - meta
  - toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
    - include-markdown
    - search
    - same-dir
    - autorefs
    - autolinks
    - gen-files:
        scripts:
          - docs/gen_api_nav.py
          - docs/gen_examples.py
    - literate-nav:
        nav_file: SUMMARY.md
    - git-revision-date-localized:
        type: timeago
        fallback_to_build_date: true
        enable_creation_date: true
        enabled: true
    - mkdocstrings:
        handlers:
          python:
            import:
              - https://docs.python.org/3/objects.inv
            rendering:
              show_root_heading: true
              show_source: false
              docstring_section_style: list
              members_order: alphabetical
              show_category_heading: no
              merge_init_into_class: yes
              how_submodules: no
            selection:
              docstring_style: google
              docstring_options:
                ignore_init_summary: yes
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
    - mkdocs_pymdownx_material_extras
