name: Python package

on: [pull_request]

jobs:
  python-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry --version
        poetry install

    - name: Run tests and linters
      run: |
        #!/bin/sh -e
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        export PREFIX="poetry run python -m "
        if [ -d 'venv' ] ; then
            export PREFIX="venv/bin/"
        fi

        ${PREFIX}black photoshop --check
        ${PREFIX}isort --check-only photoshop
        ${PREFIX}flake8 photoshop --max-line-length 120
